import type { Metadata } from "next";
import "./globals.css";
import VantaLoader from "./components/VantaLoader";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="min-h-screen text-white">
        <VantaLoader />
        <div className="relative z-10">{children}</div>
      </body>
    </html>
  );
}
